### ISSUE TITLE
Userlist can't be expanded

### ISSUE THREAD

**Issue by ir75** [Accenture/adop-ldap-phpadmin#1]
Ldapadmin works correctly and we can log in and see the list of groups. However, when we try to expand the list of users we receive the error "There was a problem with the request.". Chrome developer's tool shows that site returns 502 Bad gateway error. We destroyed container and recreated it from scratch, the issue is still there.

**Comment by avoidik** [comment]
@ir75 no more relevant, right?

**Comment by RobertNorthard** [comment]
Closing issue as no response. @ir75 please re-open if this is still relevant.
